In [1]:
import pandas as pd
import numpy as np

file_path = "../data/raw/Customer_support_data.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)

Dataset shape: (85907, 20)

In [2]:
df.head()

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01-08-2023 11:13,01-08-2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01-08-2023 12:52,01-08-2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01-08-2023 20:16,01-08-2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01-08-2023 20:56,01-08-2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01-08-2023 10:30,01-08-2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5

In [3]:
clean_df = df.copy()

In [4]:
clean_df

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01-08-2023 11:13,01-08-2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01-08-2023 12:52,01-08-2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01-08-2023 20:16,01-08-2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01-08-2023 20:56,01-08-2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01-08-2023 10:30,01-08-2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85902,505ea5e7-c475-4fac-ac36-1d19a4cb610f,Inbound,Refund Related,Refund Enquiry,NaN,1b5a2b9c-a95f-405f-a42e-5b1b693f3dc9,NaN,30-08-2023 23:20,31-08-2023 07:22,31-Aug-23,NaN,NaN,NaN,NaN,Brandon Leon,Ethan Tan,William Kim,On Job Training,Morning,4
85903,44b38d3f-1523-4182-aba2-72917586647c,Inbound,Order Related,Seller Cancelled Order,Supported team customer executive good,d0e8a817-96d5-4ace-bb82-adec50398e22,NaN,31-08-2023 08:15,31-08-2023 08:17,31-Aug-23,NaN,NaN,NaN,NaN,Linda Foster,Noah Patel,Emily Chen,>90,Morning,5
85904,723bce2c-496c-4aa8-a64b-ca17004528f0,Inbound,Order Related,Order status enquiry,need to improve with proper details.,bdefe788-ccec-4eda-8ca4-51045e68db8a,NaN,31-08-2023 18:57,31-08-2023 19:02,31-Aug-23,NaN,NaN,NaN,NaN,Kimberly Martinez,Aiden Patel,Olivia Tan,On Job Training,Evening,5
85905,707528ee-6873-4192-bfa9-a491f1c08ab5,Inbound,Feedback,UnProfessional Behaviour,NaN,a031ec28-0c5e-450e-95b2-592342c40bc4,NaN,31-08-2023 19:59,31-08-2023 20:00,31-Aug-23,NaN,NaN,NaN,NaN,Daniel Martin,Olivia Suzuki,Olivia Tan,>90,Morning,4
85906,07c7a878-0d5a-42e0-97ef-de59abec0238,Inbound,Returns,Reverse Pickup Enquiry,NaN,3230db30-f8da-4c44-8636-ec76d1d3d4f3,NaN,31-08-2023 23:36,31-08-2023 23:37,31-Aug-23,NaN,NaN,NaN,NaN,Elizabeth Guerra,Nathan Patel,Jennifer Nguyen,On Job Training,Evening,5

In [5]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

clean_df.columns.tolist()

['unique_id',
 'channel_name',
 'category',
 'sub_category',
 'customer_remarks',
 'order_id',
 'order_date_time',
 'issue_reported_at',
 'issue_responded',
 'survey_response_date',
 'customer_city',
 'product_category',
 'item_price',
 'connected_handling_time',
 'agent_name',
 'supervisor',
 'manager',
 'tenure_bucket',
 'agent_shift',
 'csat_score']

In [6]:
clean_df.duplicated().sum()

np.int64(0)

In [7]:
duplicates = clean_df[clean_df.duplicated(keep=False)]

duplicates.head(20)

Empty DataFrame
Columns: [unique_id, channel_name, category, sub_category, customer_remarks, order_id, order_date_time, issue_reported_at, issue_responded, survey_response_date, customer_city, product_category, item_price, connected_handling_time, agent_name, supervisor, manager, tenure_bucket, agent_shift, csat_score]
Index: []

In [8]:
missing = clean_df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

connected_handling_time    85665
customer_city              68828
product_category           68711
item_price                 68701
order_date_time            68693
customer_remarks           57165
order_id                   18232
dtype: int64

In [9]:
missing_percentage = (
    clean_df.isnull().mean() * 100
).sort_values(ascending=False)

missing_percentage[missing_percentage > 0]

connected_handling_time    99.718300
customer_city              80.119199
product_category           79.983005
item_price                 79.971364
order_date_time            79.962052
customer_remarks           66.542889
order_id                   21.222950
dtype: float64

In [10]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   unique_id                85907 non-null  str
 1   channel_name             85907 non-null  str
 2   category                 85907 non-null  str
 3   sub_category             85907 non-null  str
 4   customer_remarks         28742 non-null  str
 5   order_id                 67675 non-null  str
 6   order_date_time          17214 non-null  str
 7   issue_reported_at        85907 non-null  str
 8   issue_responded          85907 non-null  str
 9   survey_response_date     85907 non-null  str
 10  customer_city            17079 non-null  str
 11  product_category         17196 non-null  str
 12  item_price               17206 non-null  float64
 13  connected_handling_time  242 non-null    float64
 14  agent_name               85907 non-null  str
 15  supervisor               85907 non-null  str
 16  manager                  85907 non-null  str
 17  tenure_bucket            85907 non-null  str
 18  agent_shift              85907 non-null  str
 19  csat_score               85907 non-null  int64
dtypes: float64(2), int64(1), str(17)
memory usage: 13.1 MB

In [11]:
date_columns = [
    "order_date_time",
    "issue_reported_at",
    "issue_responded",
    "survey_response_date"
]

for col in date_columns:
    clean_df[col] = pd.to_datetime(
        clean_df[col],
        errors="coerce"
    )

C:\Users\ky582\AppData\Local\Temp\ipykernel_28080\2661136411.py:9: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  clean_df[col] = pd.to_datetime(
C:\Users\ky582\AppData\Local\Temp\ipykernel_28080\2661136411.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean_df[col] = pd.to_datetime(

In [13]:
clean_df["order_date_time"].head(10)

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
5   NaT
6   NaT
7   NaT
8   NaT
9   NaT
Name: order_date_time, dtype: datetime64[us]

In [15]:
clean_df["order_date_time"].astype(str).head(10)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: order_date_time, dtype: str

In [16]:
clean_df["order_date_time"].dropna().head(10)

11   2023-07-19 23:50:00
16   2023-05-06 21:41:00
19   2023-07-18 12:20:00
24   2023-07-15 14:47:00
25   2023-07-29 13:35:00
26   2023-07-28 10:52:00
27   2023-07-25 13:49:00
37   2023-07-19 00:11:00
50   2023-07-24 16:57:00
54   2023-07-22 13:21:00
Name: order_date_time, dtype: datetime64[us]

In [17]:
clean_df[date_columns].isnull().sum()

order_date_time         68693
issue_reported_at       53933
issue_responded         54022
survey_response_date        0
dtype: int64

In [18]:
clean_df[
    clean_df["issue_reported_at"].isnull()
][["issue_reported_at", "issue_responded"]].head()

    issue_reported_at     issue_responded
50                NaT 2023-01-08 00:04:00
54                NaT 2023-02-08 07:42:00
92                NaT 2023-01-08 12:54:00
101               NaT 2023-01-08 07:55:00
133               NaT 2023-01-08 00:17:00

In [19]:
clean_df[[
    "item_price",
    "connected_handling_time",
    "csat_score"
]].dtypes

item_price                 float64
connected_handling_time    float64
csat_score                   int64
dtype: object

In [20]:
numeric_columns = [
    "item_price",
    "connected_handling_time",
    "csat_score"
]

for col in numeric_columns:
    clean_df[col] = pd.to_numeric(
        clean_df[col],
        errors="coerce"
    )

In [21]:
clean_df["csat_score"].value_counts().sort_index()

csat_score
1    11230
2     1283
3     2558
4    11219
5    59617
Name: count, dtype: int64

In [22]:
clean_df[
    ~clean_df["csat_score"].isin([1, 2, 3, 4, 5])
]["csat_score"].value_counts()

Series([], Name: count, dtype: int64)

In [23]:
clean_df["item_price"].describe()

count     17206.000000
mean       5660.774846
std       12825.728411
min           0.000000
25%         392.000000
50%         979.000000
75%        2699.750000
max      164999.000000
Name: item_price, dtype: float64

In [24]:
clean_df[clean_df["item_price"] < 0]

Empty DataFrame
Columns: [unique_id, channel_name, category, sub_category, customer_remarks, order_id, order_date_time, issue_reported_at, issue_responded, survey_response_date, customer_city, product_category, item_price, connected_handling_time, agent_name, supervisor, manager, tenure_bucket, agent_shift, csat_score]
Index: []

customer_remarks

In [25]:
clean_df["customer_remarks"].head(10)

0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
5                                                  NaN
6                                                  NaN
7                                            Very good
8    Shopzilla app and it's all coustomer care serv...
9                                                  NaN
Name: customer_remarks, dtype: str

In [26]:
clean_df["customer_remarks"] = (
    clean_df["customer_remarks"]
    .astype("string")
    .str.strip()
)

In [27]:
clean_df["customer_remarks"] = (
    clean_df["customer_remarks"]
    .replace("", pd.NA)
)

In [28]:
clean_df["category"].value_counts()

category
Returns               44097
Order Related         23215
Refund Related         4550
Product Queries        3692
Shopzilla Related      2792
Payments related       2327
Feedback               2294
Cancellation           2212
Offers & Cashback       480
Others                   99
App/website              84
Onboarding related       65
Name: count, dtype: int64

In [29]:
clean_df["sub_category"].value_counts()

sub_category
Reverse Pickup Enquiry              22389
Return request                       8523
Delayed                              7388
Order status enquiry                 6922
Installation/demo                    4116
Fraudulent User                      4108
Product Specific Information         3589
Refund Enquiry                       2665
Wrong                                2597
Missing                              2556
UnProfessional Behaviour             2294
General Enquiry                      1945
Not Needed                           1920
Service Centres Related              1875
Refund Related Issues                1800
Invoice request                      1465
Online Payment Issues                1079
Seller Cancelled Order               1059
Priority delivery                     972
Exchange / Replacement                896
Customer Requested Modifications      805
Payment related Queries               743
Signup Issues                         489
Damaged                               475
Technician Visit                      378
Shopzila Premium Related              361
Return cancellation                   292
Wallet related                        230
Other Cashback                        219
Product related Issues                183
Affiliate Offers                      183
Unable to track                       164
Account updation                      150
PayLater related                      140
COD Refund Details                     85
Shopzilla Rewards                      80
Instant discount                       78
Warranty related                       78
Issues with Shopzilla App              74
Order Verification                     72
Seller onboarding                      62
Service Center - Service Denial        58
Billing Related                        57
Self-Help                              49
Call back request                      46
e-Gift Voucher                         42
Call disconnected                      40
Life Insurance                         23
Other Account Related Issues           22
Card/EMI                               19
Payment pending                        17
Others                                 12
App/website Related                    10
Unable to Login                         7
Commission related                      3
Policy Related                          2
Non Order related                       1
Name: count, dtype: int64

In [30]:
clean_df["channel_name"].value_counts()

channel_name
Inbound    68142
Outcall    14742
Email       3023
Name: count, dtype: int64

In [31]:
clean_df["channel_name"] = (
    clean_df["channel_name"]
    .str.strip()
    .str.lower()
)

response_time_minutes

In [32]:
clean_df["response_time_minutes"] = (
    clean_df["issue_responded"] -
    clean_df["issue_reported_at"]
).dt.total_seconds() / 60

In [33]:
clean_df["response_time_minutes"].describe()

count     31633.000000
mean       4647.152214
std       17113.187472
min           0.000000
25%           2.000000
50%           6.000000
75%          41.000000
max      177097.000000
Name: response_time_minutes, dtype: float64

In [34]:
clean_df[
    clean_df["response_time_minutes"] < 0
].shape

(0, 21)

response_time_BUCKETS

In [38]:
bins = [-1, 15, 30, 60, 240, 1440, np.inf]

labels = [
    "<15 min",
    "15–30 min",
    "30–60 min",
    "1–4 hours",
    "4–24 hours",
    "24+ hours"
]

clean_df["response_time_bucket"] = pd.cut(
    clean_df["response_time_minutes"],
    bins=bins,
    labels=labels
)

In [39]:
def classify_csat(score):
    if pd.isna(score):
        return pd.NA
    elif score <= 2:
        return "Dissatisfied"
    elif score == 3:
        return "Neutral"
    else:
        return "Satisfied"

clean_df["csat_category"] = (
    clean_df["csat_score"].apply(classify_csat)
)

In [40]:
clean_df["csat_category"].value_counts()

csat_category
Satisfied       70836
Dissatisfied    12513
Neutral          2558
Name: count, dtype: int64

Save the cleaned dataset

In [41]:
output_path = "../data/processed/customer_support_cleaned.csv"

clean_df.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [42]:
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])

print("\nMissing values:")
display(
    clean_df.isnull().sum()
    .sort_values(ascending=False)
    .head(10)
)

print("\nDuplicate rows:", clean_df.duplicated().sum())

print("\nData types:")
display(clean_df.dtypes)

print("\nCSAT:")
display(clean_df["csat_score"].value_counts().sort_index())

print("\nSample:")
display(clean_df.head())

Rows: 85907
Columns: 23

Missing values:

connected_handling_time    85665
customer_city              68828
product_category           68711
item_price                 68701
order_date_time            68693
customer_remarks           57165
response_time_minutes      54274
response_time_bucket       54274
issue_responded            54022
issue_reported_at          53933
dtype: int64

Duplicate rows: 0

Data types:

unique_id                             str
channel_name                          str
category                              str
sub_category                          str
customer_remarks                   string
order_id                              str
order_date_time            datetime64[us]
issue_reported_at          datetime64[us]
issue_responded            datetime64[us]
survey_response_date       datetime64[us]
customer_city                         str
product_category                      str
item_price                        float64
connected_handling_time           float64
agent_name                            str
supervisor                            str
manager                               str
tenure_bucket                         str
agent_shift                           str
csat_score                          int64
response_time_minutes             float64
response_time_bucket             category
csat_category                         str
dtype: object

CSAT:

csat_score
1    11230
2     1283
3     2558
4    11219
5    59617
Name: count, dtype: int64

Sample:

,unique_id,channel_name,category,sub_category,customer_remarks,order_id,order_date_time,issue_reported_at,issue_responded,survey_response_date,...,connected_handling_time,agent_name,supervisor,manager,tenure_bucket,agent_shift,csat_score,response_time_minutes,response_time_bucket,csat_category
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,outcall,Product Queries,Life Insurance,<NA>,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaT,2023-01-08 11:13:00,2023-01-08 11:47:00,2023-08-01,...,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5,34.0,30–60 min,Satisfied
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,outcall,Product Queries,Product Specific Information,<NA>,d406b0c7-ce17-4654-b9de-f08d421254bd,NaT,2023-01-08 12:52:00,2023-01-08 12:54:00,2023-08-01,...,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5,2.0,<15 min,Satisfied
2,200814dd-27c7-4149-ba2b-bd3af3092880,inbound,Order Related,Installation/demo,<NA>,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaT,2023-01-08 20:16:00,2023-01-08 20:38:00,2023-08-01,...,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5,22.0,15–30 min,Satisfied
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,inbound,Returns,Reverse Pickup Enquiry,<NA>,5aed0059-55a4-4ec6-bb54-97942092020a,NaT,2023-01-08 20:56:00,2023-01-08 21:16:00,2023-08-01,...,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5,20.0,15–30 min,Satisfied
4,ba903143-1e54-406c-b969-46c52f92e5df,inbound,Cancellation,Not Needed,<NA>,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaT,2023-01-08 10:30:00,2023-01-08 10:32:00,2023-08-01,...,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5,2.0,<15 min,Satisfied

In [43]:
missing_summary = pd.DataFrame({
    "missing_count": clean_df.isnull().sum(),
    "missing_percentage": clean_df.isnull().mean() * 100
})

missing_summary = missing_summary.sort_values(
    "missing_percentage",
    ascending=False
)

display(missing_summary)

                         missing_count  missing_percentage
connected_handling_time          85665           99.718300
customer_city                    68828           80.119199
product_category                 68711           79.983005
item_price                       68701           79.971364
order_date_time                  68693           79.962052
customer_remarks                 57165           66.542889
response_time_minutes            54274           63.177622
response_time_bucket             54274           63.177622
issue_responded                  54022           62.884282
issue_reported_at                53933           62.780681
order_id                         18232           21.222950
sub_category                         0            0.000000
unique_id                            0            0.000000
channel_name                         0            0.000000
category                             0            0.000000
agent_name                           0            0.000000
survey_response_date                 0            0.000000
supervisor                           0            0.000000
manager                              0            0.000000
agent_shift                          0            0.000000
tenure_bucket                        0            0.000000
csat_score                           0            0.000000
csat_category                        0            0.000000

In [44]:
clean_df = clean_df.drop(
    columns=["connected_handling_time"]
)

print(clean_df.shape)

(85907, 22)

In [45]:
clean_df["has_customer_remark"] = (
    clean_df["customer_remarks"].notna()
)

clean_df["has_order_info"] = (
    clean_df["order_id"].notna()
)

clean_df["has_response_time"] = (
    clean_df["response_time_minutes"].notna()
)

In [46]:
print(
    clean_df["has_customer_remark"].value_counts()
)

print(
    clean_df["has_order_info"].value_counts()
)

print(
    clean_df["has_response_time"].value_counts()
)

has_customer_remark
False    57165
True     28742
Name: count, dtype: int64
has_order_info
True     67675
False    18232
Name: count, dtype: int64
has_response_time
False    54274
True     31633
Name: count, dtype: int64

In [47]:
support_df = clean_df.copy()

In [48]:
sentiment_df = clean_df[
    clean_df["customer_remarks"].notna()
].copy()

In [49]:
print("Sentiment dataset:", sentiment_df.shape)

Sentiment dataset: (28742, 25)

In [50]:
response_df = clean_df[
    clean_df["response_time_minutes"].notna()
].copy()

In [51]:
print("Response-time dataset:", response_df.shape)

Response-time dataset: (31633, 25)

In [52]:
print("MAIN SUPPORT DATA")
print(support_df.shape)

print("\nSENTIMENT DATA")
print(sentiment_df.shape)

print("\nRESPONSE-TIME DATA")
print(response_df.shape)

MAIN SUPPORT DATA
(85907, 25)

SENTIMENT DATA
(28742, 25)

RESPONSE-TIME DATA
(31633, 25)

In [53]:
print(
    clean_df["category"]
    .value_counts()
)

category
Returns               44097
Order Related         23215
Refund Related         4550
Product Queries        3692
Shopzilla Related      2792
Payments related       2327
Feedback               2294
Cancellation           2212
Offers & Cashback       480
Others                   99
App/website              84
Onboarding related       65
Name: count, dtype: int64

In [54]:
print(
    clean_df["sub_category"]
    .value_counts()
    .head(30)
)

sub_category
Reverse Pickup Enquiry              22389
Return request                       8523
Delayed                              7388
Order status enquiry                 6922
Installation/demo                    4116
Fraudulent User                      4108
Product Specific Information         3589
Refund Enquiry                       2665
Wrong                                2597
Missing                              2556
UnProfessional Behaviour             2294
General Enquiry                      1945
Not Needed                           1920
Service Centres Related              1875
Refund Related Issues                1800
Invoice request                      1465
Online Payment Issues                1079
Seller Cancelled Order               1059
Priority delivery                     972
Exchange / Replacement                896
Customer Requested Modifications      805
Payment related Queries               743
Signup Issues                         489
Damaged                               475
Technician Visit                      378
Shopzila Premium Related              361
Return cancellation                   292
Wallet related                        230
Other Cashback                        219
Product related Issues                183
Name: count, dtype: int64

In [55]:
print(
    clean_df["channel_name"]
    .value_counts()
)

channel_name
inbound    68142
outcall    14742
email       3023
Name: count, dtype: int64

In [56]:
clean_df.to_csv(
    "../data/processed/customer_support_cleaned.csv",
    index=False
)

sentiment_df.to_csv(
    "../data/processed/customer_support_sentiment.csv",
    index=False
)

response_df.to_csv(
    "../data/processed/customer_support_response_time.csv",
    index=False
)

print("All cleaned datasets saved successfully.")

All cleaned datasets saved successfully.